spring:
  mvc:
    static-path-pattern: /static/**
  data:
    rest.base-path: /api
    datasource:
    url: jdbc:h2:mem:testdb:CREATE SCHEMA IF NOT EXISTS ESTORE
    driverClassName:  org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform:
      properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: creare-drop
      show-sql: true
      properties.hibernate.globally_quoted_identifiers: true

server:
  port: 8081
  servlet:
     context-path: /estore

#springdoc.packages-to-scan: com.online.estore.api.controller
