spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    properties.hibernate.globally_quoted_identifiers: false
  flyway:
    locations: classpath:db/migration/h2

server:
  port: 8081
  servlet:
    context-path: /estore-web
