spring:
  mvc:
    static-path-pattern: /static/**
  data:
    rest.base-path: /api
    datasource:
    url: jdbc:h2:mem:testdb
    driverClassName:  org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform:
      properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: update
      show-sql: true
      properties.hibernate.globally_quoted_identifiers: true
  http:
    converters:
      preferred-json-mapper: gson
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: INFO
    #web: DEBUG
server:
  port: 8081
  servlet:
     context-path: /estore-ws

---
spring:
   profile: openshift
   data:
      datasource:
        url: jdbc:h2:mem:testdb
        driverClassName:  org.h2.Driver
        username: sa
        password:
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect




