spring:
  mvc:
    static-path-pattern: /static/**
  data:
    rest.base-path: /api
    datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:/data/demo
    driverClassName:  org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
    #properties.hibernate.dialect: org.postgresql.Driver
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.globally_quoted_identifiers: true

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: debug
    org.springframework: INFO
    #web: DEBUG

server:
  port: 8080
  servlet:
     context-path: /estore-ws



