spring:
  mvc:
    static-path-pattern: /static/**
  data:
    rest.base-path: /api
    #datasource:
    #url: jdbc:mysql://localhost:3306/estore?useSSL=false
    #username: root
    #password: root
  jpa:
    #properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.globally_quoted_identifiers: true

#logging
logging:
  pattern.console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    org.hibernate.SQL: debug
    org.springframework: DEBUG
    web: DEBUG

server:
  port: 8080
  servlet.context-path: /estore-ws


