spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.globally_quoted_identifiers: false
  flyway:
    locations: classpath:db/migration/h2

server:
  port: 8083
  servlet:
    context-path: /estore-auth

h2.console.enabled: true
springdoc.packages-to-scan: com.online.estore.auth.api.controller


