spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://db-estore:5432/postgres
    tomcat:
      initial-size: 10
      max-active: 50
      max-wait: 10000
      test-on-borrow: true