version: '3.3'
services:
  estore:
    image: "estore-app:latest"
    ports:
       - 9010:8082
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1536M
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: pause
    hostname: estore-app
    depends_on:
          - db-estore
    volumes:
      - ${LOGS_VOLUME:-logs}:/home/appuser/logs
      - ./config/dev/application.yml:/opt/app/java/config/application.dev.yml:ro
      - ./config/application.yml:/opt/app/java/config/application.yml:ro
      - ./config/logback-console.xml:/opt/app/java/config/logback.xml:ro
    networks:
      - network
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=70
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME:-Test}
      - OVEROPS=${OVEROPS:-false}
      #- LOCAL_USER_ID=${LOCAL_USER_ID:-9001}
      - SPRING_CONFIG_LOCATION=file:./config/
      - SPRING_PROFILES_ACTIVE=boot #,${ENV}
  db-estore:
    image: "postgres:latest"
    ports:
       - 23331:5432
    deploy:
      replicas: 1
      #placement:
        #constraints:
          #- node.labels.com.rambus.payments.db.node == true
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: pause
    hostname: db-estore
    volumes:
      - dbdata-estore:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: overlay
    attachable: true

volumes:
  logs:
  dbdata-estore:

