version: '3.3'
services:
   e-store:
    configs:
      #- source: estore-application-env
      #  target: /opt/app/java/config/application-${ENV}.yml
      - source: estore-application
        target: /opt/app/java/config/application.yml
      - source: logback
       target: /opt/app/java/config/logback.xml

configs:
  logback:
    file: ./config/logback-console.xml
   estore-application-env:
    #file: ./config/${ENV}/application.yml
    file: ./config/dev/application.yml
  estore-application:
    file: ./config/application.yml
