spring:
  application:
    name: estore
  data:
    rest.base-path: /api
  cache:
    caffeine.spec: maximumSize=500, expireAfterWrite=60s
  info:
    git:
      location: classpath:META-INF/git.properties

server:
  port: 8082
  servlet:
    context-path: /estore/
    session:
      cookie:
        http-only: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  config: /opt/app/java/config/logback.xml

management:
  info:
    git:
      mode: simple
  endpoint:
    health:
      show-details: always
  server:
    port: 8181
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health,prometheus"
